### ISSUE TITLE
Readme - Technologies used

### ISSUE THREAD

**Issue by kera-cudmore** [andrewdempsey2018/Found-In-Translation#16]
Languages Used

- [x] HTML
- [x] CSS
- [x] JavaScript
- [x] Python

Frameworks, Libraries & Programs used
- [x] Figma
- [x] Git
- [x] GitHub
- [x] Google Fonts?
- [x] Google Dev Tools
- [x] Tinypng ?
- [x] Birme - to convert files to webp format
- [x] Favicon.io
- [x] amiresponsive - (is there something that works better?)
- [x] shields.io
- [x] Bootstrap version 5.2
- [x] Flask
- [x] Jinja
- [x] mongodb

**Comment by paulasdev** [comment]
I added Heroku
